### ISSUE TITLE
Model and data files access

### ISSUE THREAD

**Issue by hrishikeshvganu** [personalizedretrieval/xpert#4]
Looks like the model and data files are not publicly accessible. Is this intended?

wget https://ecstorageaccount.blob.core.windows.net/eoe/data.zip
  https://ecstorageaccount.blob.core.windows.net/eoe/data.zip
Resolving ecstorageaccount.blob.core.windows.net (ecstorageaccount.blob.core.windows.net)... 20.60.153.33
Connecting to ecstorageaccount.blob.core.windows.net (ecstorageaccount.blob.core.windows.net)|20.60.153.33|:443... connected.
HTTP request sent, awaiting response... 409 Public access is not permitted on this storage account.

**Comment by shivam-msft** [comment]
We've updated the models and data files link in the README. Can you try now?

**Comment by shivam-msft** [comment]
Closing for now. Please feel free to open if there is any issue.
