### ISSUE TITLE
Working Example.

### ISSUE THREAD

**Issue by NitinAggarwal1** [personalizedretrieval/xpert#5]
Hi @shivam-msft  . It’s a great paper and I am looking to use NGAME embeddings for my product search task to implement via XPERT to benchmark against some of baseline approach . 

Can you please guide on some working example for training the morph operator and overall using the  XPERT

**Comment by shivam-msft** [comment]
Hi Nitin, for now we haven't added the code for training the morph operators yet. We will try to add it in the near future.
We have the instructions for using the inference code in the README. Let us know if you face any issues with them.

**Comment by NitinAggarwal1** [comment]
Thanks for the response Shivam. Looking forward to try XPERT end to end
