### ISSUE TITLE
Models folder is not present.

### ISSUE THREAD

**Issue by NitinAggarwal1** [personalizedretrieval/xpert#7]
Hi , I think the two data directories shared are exactly same and missed uploading the model file.

**Comment by Sheshansh** [comment]
Thanks for pointing out, can you check again? (Added one more link in README for model)

**Comment by NitinAggarwal1** [comment]
The model file looks right now . I have downloaded and checked . I will let it run the evaluation once just like you mentioned and let you know if anything needs attention .  Thanks for the quick response . 

Looking forward to train using XPERT from scratch .  Will be waiting for the rest of the To Do.
